package com.sakayori.peek

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.max
import kotlin.math.min

/**
 * The port must reproduce peek-vanilla's SVGs byte-for-byte.
 * Corpus generated by gen-corpus.mjs (node gen-corpus.mjs to regenerate).
 */
class PeekGoldenTest {

    @Test
    fun goldenCorpus() {
        assertTrue("empty corpus", GOLDEN_CORPUS.isNotEmpty())
        var bad = 0
        for ((i, c) in GOLDEN_CORPUS.withIndex()) {
            val actual = toSvg(c.name, c.opts)
            if (actual != c.expected) {
                bad++
                if (bad <= 3) {
                    System.err.println("MISMATCH case $i name=${c.name} opts=${c.opts}")
                    val pos = actual.zip(c.expected).indexOfFirst { (a, b) -> a != b }
                    System.err.println("  first diff at char $pos (lengths ${actual.length} vs ${c.expected.length})")
                    if (pos >= 0) {
                        val lo = max(0, pos - 60)
                        System.err.println("  actual  : …${actual.substring(lo, min(actual.length, pos + 60))}…")
                        System.err.println("  expected: …${c.expected.substring(lo, min(c.expected.length, pos + 60))}…")
                    }
                }
            }
        }
        assertEquals("$bad/${GOLDEN_CORPUS.size} cases mismatched", 0, bad)
    }

    @Test
    fun identifyIsDeterministic() {
        val a = identify("Sakayori")
        val b = identify("Sakayori")
        assertEquals(a, b)
        // tidy(): case/space-insensitive
        assertEquals(identify("  SAKAYORI  ").face, a.face)
        assertEquals(identify("sakayori").color, a.color)
    }

    @Test
    fun tidyNfc() {
        // e + combining acute normalizes to the same key as é
        assertEquals(identify("é").key, identify("é").key)
    }
}
